name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}

    defaults:
      run:
        shell: ${{ matrix.platform.shell }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: Linux (CMake), os: ubuntu-latest, shell: sh, flags: true }

    steps:
      - name: Setup Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install \
            build-essential \
            python3 \
            cmake \
            git
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Configure EMSDK (Linux)
        if: runner.os == 'Linux'
        run: |
          echo '=== move to emsdk directory'
          cd ./harpia/third_party/emsdk/
          echo '=== git pull'
          git pull
          echo '=== install latest'
          ./emsdk install latest
          echo '=== activate latest'
          ./emsdk activate latest
          echo '=== set env'
          echo 'source "./emsdk_env.sh"' >> $HOME/.bash_profile
          export PATH="./harpia/third_party/emsdk/upstream/emscripten/:$PATH"
      - name: Compile test file
        if: runner.os == 'Linux'
        run: |
          echo '=== Set Toolchain File'
          CMAKE_TOOLCHAIN_FILE=./harpia/third_party/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake
          mkdir build
          cd build
          emcmake cmake ..
          make