name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}

    defaults:
      run:
        shell: ${{ matrix.platform.shell }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: Linux (CMake), os: ubuntu-latest, shell: sh, flags: true }

    steps:
      - name: Setup Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install \
            build-essential \
            python3 \
            cmake \
            git
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Configure EMSDK (Linux)
        if: runner.os == 'Linux'
        run: |
          echo '=== move to emsdk directory'
          cd ./harpia/third_party/emsdk/
          echo '=== git pull'
          git pull
          echo '=== install latest'
          ./emsdk install latest
          echo '=== activate latest'
          ./emsdk activate latest
          echo '=== set env'
          echo 'source "./emsdk_env.sh"' >> $HOME/.bash_profile
      - name: Compile test file
        if: runner.os == 'Linux'
        run: |
          ./harpia/third_party/emsdk/upstream/emscripten/emcc -v
          echo '=== Compile C'
          ./harpia/third_party/emsdk/upstream/emscripten/emcc ./emcc_test.c -o ./index.html
          echo '===index.html'
          cat ./index.html
          echo '=== Compile C++'
          ./harpia/third_party/emsdk/upstream/emscripten/em++ ./empp_test.cpp -o ./index.html
          echo '===index.html'
          cat ./index.html