name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}

    defaults:
      run:
        shell: ${{ matrix.platform.shell }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: Linux (CMake), os: ubuntu-latest, shell: sh, flags: true }

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: mymindstorm/setup-emsdk@v10
        with:
          version: 2.0.27
      - name: Build WebGL
        if: runner.os == 'Linux'
        run: |
          echo '=== Set Toolchain File'
          CMAKE_TOOLCHAIN_FILE=./harpia/third_party/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake
          mkdir build
          cd build
          echo '=== emcmake'
          ../harpia/third_party/emsdk/upstream/emscripten/emcmake cmake ..
          echo '=== make'
          make
      - name: Print Build Logs
        if: always()
        run: |
          if test -f "/home/runner/work/harpia-game-engine/harpia-game-engine/build/CMakeFiles/CMakeOutput.log"; then
              echo "=== cat /home/runner/work/harpia-game-engine/harpia-game-engine/build/CMakeFiles/CMakeOutput.log"
              cat /home/runner/work/harpia-game-engine/harpia-game-engine/build/CMakeFiles/CMakeOutput.log
          fi
          if test -f "/home/runner/work/harpia-game-engine/harpia-game-engine/build/CMakeFiles/CMakeError.log"; then
              echo "=== cat /home/runner/work/harpia-game-engine/harpia-game-engine/build/CMakeFiles/CMakeError.log"
              cat /home/runner/work/harpia-game-engine/harpia-game-engine/build/CMakeFiles/CMakeError.log
          fi