name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}

    defaults:
      run:
        shell: ${{ matrix.platform.shell }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: Linux (CMake), os: ubuntu-latest, shell: sh, flags: true }

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          chmod -R 777 ./build_scripts \
          ./build_scripts/setup_linux.sh
      - name: Tests
        if: runner.os == 'Linux'
        run: |
          cmake -S . -B tests-build/ --verbose --target Harpia.Tests
          ./tests-build/bin/Harpia.Tests --gtest_color=no
      - uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.24
      - name: Setup gl3w
        if: runner.os == 'Linux'
        run: python ./harpia/third_party/gl3w/gl3w_gen.py
      - name: Configure Emcmake CMake
        run: |
          emcmake cmake -S . -B build \
            -DSDL_TESTS=ON \
            -DSDL_INSTALL_TESTS=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=prefix
      - name: Print Build Logs
        if: always()
        run: |
          if test -f "/home/runner/work/harpia-game-engine/harpia-game-engine/build/CMakeFiles/CMakeOutput.log"; then
              echo "=== cat /home/runner/work/harpia-game-engine/harpia-game-engine/build/CMakeFiles/CMakeOutput.log"
              cat /home/runner/work/harpia-game-engine/harpia-game-engine/build/CMakeFiles/CMakeOutput.log
          fi
          if test -f "/home/runner/work/harpia-game-engine/harpia-game-engine/build/CMakeFiles/CMakeError.log"; then
              echo "=== cat /home/runner/work/harpia-game-engine/harpia-game-engine/build/CMakeFiles/CMakeError.log"
              cat /home/runner/work/harpia-game-engine/harpia-game-engine/build/CMakeFiles/CMakeError.log
          fi